os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge
language: php
php:
  - 7.4
services:
  - mysql
before_script:
  - mysql -V
  - uname -p
  - mysqladmin -u root password ''
  - sudo mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
script: true
