os: linux
dist: focal
arch: arm64-graviton2
language: php
php:
  - 7.4
services:
  - mysql
before_script:
  - sudo mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
script: true