os: linux
dist: bionic
arch: arm64-graviton2
virt: lxd
group: edge
language: php
php:
  - 7.4
services:
  - mysql
before_script:
  - mysql -V
  - uname -p
  - mysql -u root -h 127.0.0.1 -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
script: true