os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge
language: php
php:
  - 7.4
services:
  - mysql
install:
  - |
    if [[ $TRAVIS_CPU_ARCH == "arm64" ]]; then
      sudo bash -ec '
      echo -e '\''[mysqld]\\nskip-grant-tables'\'' >/etc/mysql/conf.d/grant.cnf
      systemctl restart mysql
      mysql -e "UPDATE mysql.user SET Grant_priv='\''Y'\'', Super_priv='\''Y'\'' WHERE User='\''root'\''; flush privileges;"
      rm /etc/mysql/conf.d/grant.cnf
      systemctl restart mysql'
    fi
before_script:
  - mysql -V
  - uname -p
#  - mysqladmin -u root password ''
  - sudo mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'%' IDENTIFIED BY 'drupal'; GRANT ALL PRIVILEGES ON drupal.* TO 'drupal'@'%';"
script: true
